### ISSUE TITLE
Nullify columns not in input for an upsert

### ISSUE THREAD

**Issue by vetrady** [americanexpress/bloom#1]
**Current Description of the functionality**
For a Delta Load, the input file can have data for all the columns or for a few columns only, In-case the input has data of only for few columns and the same record is not present already ,it insert the incoming columns and null for the remaining columns. And in-case the record already exists and but is older it updates the incoming columns but keeps the other column intact. 

_It will be good to have a feature to be able to nullify columns not present in the input record in case of an upsert_ rather than keeping it intact

**Comment by DeanJain** [comment]
Great Idea, thanks for the feedback @vetrady. will implement this as a new feature, config driven mechanism so that user can choose if he wants update or upsert.

**Comment by DeanJain** [comment]
resolved 👍 
https://github.com/americanexpress/bloom/commit/d38f190e32432a0f525d3bd7cb478491de2d027d
